export type ServiceCategory = "STRATEGY" | "MARKETING" | "CREATIVE" | "TECHNOLOGY" | "COMMERCE" | "DATA & AUTOMATION";

export interface ServiceData {
  id: string;
  slug: string;
  category: ServiceCategory;
  categoryNumber: string;
  title: string;
  shortDescription: string;
  overview: string;
  deliverables: string[];
  process: string[];
  seoTitle: string;
  seoDescription: string;
}

export const servicesData: ServiceData[] = [
  // 01 STRATEGY
  {
    id: "brand-strategy",
    slug: "brand-strategy",
    category: "STRATEGY",
    categoryNumber: "01",
    title: "Brand Strategy",
    shortDescription: "Define your positioning, audience, and differentiation to build a brand that lasts.",
    overview: "A strong brand is more than just a logo—it's the core system that dictates how the world perceives your business. Our Brand Strategy service uncovers your unique value proposition and structures it into a cohesive identity. We help you find your voice, define your audience, and build the architectural foundation required to outposition competitors and scale with clarity.",
    deliverables: ["Brand Positioning", "Target Audience Personas", "Core Messaging Architecture", "Brand Differentiation", "Tone of Voice", "Visual Direction Strategy"],
    process: ["Discovery & Audit", "Market Research", "Positioning Development", "Messaging Framework", "Validation", "Implementation Guidelines"],
    seoTitle: "Brand Strategy Services | IGR Marketing",
    seoDescription: "Build a lasting brand with IGR Marketing. We define your positioning, audience, and differentiation to outposition competitors and scale with clarity.",
  },
  {
    id: "growth-strategy",
    slug: "growth-strategy",
    category: "STRATEGY",
    categoryNumber: "01",
    title: "Growth Strategy",
    shortDescription: "Align product, marketing, and sales to unlock compounding, sustainable revenue growth.",
    overview: "True growth is a system, not a single campaign. Our Growth Strategy focuses on identifying the highest-leverage opportunities across your entire funnel. We analyze your customer acquisition cost, lifetime value, and market dynamics to engineer a tailored roadmap. We align your product, marketing, and sales efforts to unlock compounding revenue growth that is both aggressive and sustainable.",
    deliverables: ["Funnel Analysis", "Growth Modeling", "Channel Prioritization", "Retention Strategy", "Unit Economics Mapping", "Growth Roadmapping"],
    process: ["Data Deep-Dive", "Funnel Mapping", "Opportunity Sizing", "Strategy Formulation", "Execution Planning", "Ongoing Alignment"],
    seoTitle: "Growth Strategy Services | IGR Marketing",
    seoDescription: "Unlock sustainable revenue growth with IGR Marketing's data-driven growth strategy, aligning product, marketing, and sales for compounding success.",
  },
  {
    id: "market-research",
    slug: "market-research",
    category: "STRATEGY",
    categoryNumber: "01",
    title: "Market Research",
    shortDescription: "Actionable insights and data to navigate market dynamics and outsmart your competition.",
    overview: "Operating on assumptions is a liability. Our Market Research service provides deep, empirical insights into your industry, competitors, and target demographics. We deploy quantitative and qualitative methodologies to uncover what your audience truly wants, where the market is heading, and how you can capitalize on emerging gaps before the competition does.",
    deliverables: ["Competitor Analysis", "Industry Trend Reports", "Consumer Behavior Insights", "Market Sizing", "Pricing Strategy Research", "White Space Identification"],
    process: ["Objective Definition", "Data Collection", "Competitive Benchmarking", "Trend Analysis", "Synthesis", "Actionable Reporting"],
    seoTitle: "Market Research Services | IGR Marketing",
    seoDescription: "Gain a competitive edge with IGR Marketing's deep market research. Discover actionable insights, competitor analysis, and consumer behavior data.",
  },
  {
    id: "go-to-market-strategy",
    slug: "go-to-market-strategy",
    category: "STRATEGY",
    categoryNumber: "01",
    title: "Go-To-Market Strategy",
    shortDescription: "Launch products with precision, maximum impact, and a clear path to early traction.",
    overview: "A great product needs a flawless launch. Our Go-To-Market (GTM) Strategy ensures you hit the ground running with the right message, channels, and timing. Whether you are launching a new startup, releasing a feature, or entering a new geographic market, we engineer a coordinated rollout plan that drives immediate traction and establishes strong market positioning from day one.",
    deliverables: ["Launch Phasing", "Channel Strategy", "Pricing & Packaging", "Sales Enablement", "Campaign Orchestration", "Success Metrics"],
    process: ["Product Alignment", "Market Definition", "Launch Planning", "Asset Development", "Execution", "Post-Launch Review"],
    seoTitle: "Go-To-Market Strategy | IGR Marketing",
    seoDescription: "Launch products flawlessly with IGR Marketing's Go-To-Market strategy. We engineer coordinated rollouts for maximum impact and immediate traction.",
  },

  // 02 MARKETING
  {
    id: "performance-marketing",
    slug: "performance-marketing",
    category: "MARKETING",
    categoryNumber: "02",
    title: "Performance Marketing",
    shortDescription: "Build predictable acquisition around the channels that actually move revenue.",
    overview: "Stop guessing which ads work. Our Performance Marketing service focuses entirely on measurable ROI and profitable customer acquisition. We structure, deploy, and meticulously optimize paid campaigns across search, social, and programmatic networks. By treating ad spend as an investment portfolio, we scale what works, pause what doesn't, and engineer predictable revenue engines.",
    deliverables: ["Paid Search (Google/Bing)", "Paid Social (Meta/LinkedIn)", "Campaign Structure & Strategy", "Audience Targeting", "Creative Testing Frameworks", "Budget Allocation", "Conversion Tracking"],
    process: ["Account Audit", "Strategy & Forecasting", "Campaign Build", "Launch", "A/B Testing", "Scale & Optimize"],
    seoTitle: "Performance Marketing Services | IGR Marketing",
    seoDescription: "Drive predictable revenue with IGR Marketing's Performance Marketing. We optimize paid search and social campaigns for measurable ROI and scalable growth.",
  },
  {
    id: "search-engine-optimization",
    slug: "search-engine-optimization",
    category: "MARKETING",
    categoryNumber: "02",
    title: "Search Engine Optimization",
    shortDescription: "Dominate search results and capture high-intent organic traffic predictably.",
    overview: "SEO is a compounding asset. We don't just chase algorithms; we build technical and content authority that aligns with user intent. Our approach to Search Engine Optimization bridges technical architecture, comprehensive content strategy, and authoritative link building to ensure your brand captures high-intent traffic and maintains long-term visibility in an evolving search landscape.",
    deliverables: ["Technical SEO Audits", "Keyword Strategy & Mapping", "Content Architecture", "On-Page Optimization", "Internal Linking Strategy", "Authority Building"],
    process: ["Technical Audit", "Keyword Research", "On-Page Execution", "Content Gap Filling", "Off-Page Strategy", "Monthly Monitoring"],
    seoTitle: "Search Engine Optimization (SEO) | IGR Marketing",
    seoDescription: "Capture high-intent organic traffic with IGR Marketing's technical and content-driven SEO strategies for long-term search dominance.",
  },
  {
    id: "social-media-marketing",
    slug: "social-media-marketing",
    category: "MARKETING",
    categoryNumber: "02",
    title: "Social Media Marketing",
    shortDescription: "Build a brand ecosystem that drives engagement, community, and conversion.",
    overview: "Social media is where your brand lives and breathes. We build organic social ecosystems that do more than just broadcast; they build community and drive action. From platform-specific strategies to community management and trend capitalization, we position your brand natively on the platforms where your audience spends their time, turning attention into affinity and affinity into revenue.",
    deliverables: ["Platform Strategy", "Content Calendars", "Community Management", "Trend Capitalization", "Organic Growth Tactics", "Social Listening"],
    process: ["Audience Mapping", "Content Pillar Definition", "Asset Creation", "Publishing & Engagement", "Performance Review", "Strategy Refinement"],
    seoTitle: "Social Media Marketing Agency | IGR Marketing",
    seoDescription: "Build community and drive conversion with IGR Marketing's organic social media strategies tailored for modern brand ecosystems.",
  },
  {
    id: "content-marketing",
    slug: "content-marketing",
    category: "MARKETING",
    categoryNumber: "02",
    title: "Content Marketing",
    shortDescription: "Establish authority and educate your audience with high-value, strategic content.",
    overview: "Content is the fuel for your entire marketing engine. We design content marketing strategies that educate, entertain, and convert. By producing high-value, deeply researched assets—from whitepapers and technical blogs to engaging newsletters—we help you capture attention at the top of the funnel and nurture trust all the way through to the point of sale.",
    deliverables: ["Content Strategy", "Editorial Planning", "Blog & Article Writing", "Whitepapers & E-Books", "Newsletter Management", "Content Distribution"],
    process: ["Content Audit", "Topic Ideation", "Creation & Editing", "SEO Integration", "Distribution Strategy", "Performance Analysis"],
    seoTitle: "Content Marketing Services | IGR Marketing",
    seoDescription: "Establish authority and drive conversions with IGR Marketing's strategic content marketing, from technical blogs to high-value whitepapers.",
  },
  {
    id: "email-marketing",
    slug: "email-marketing",
    category: "MARKETING",
    categoryNumber: "02",
    title: "Email Marketing",
    shortDescription: "Maximize lifetime value through automated, personalized lifecycle communication.",
    overview: "Your email list is one of the few channels you actually own. We build sophisticated email marketing programs designed to nurture leads, drive repeat purchases, and prevent churn. By combining deep segmentation, behavioral triggers, and compelling copywriting, we turn your database into a highly profitable, automated revenue channel.",
    deliverables: ["Lifecycle Automation", "Campaign Management", "List Segmentation", "A/B Testing", "Deliverability Audits", "Custom Template Design"],
    process: ["Database Audit", "Journey Mapping", "Copy & Design", "Automation Setup", "Launch", "Ongoing Optimization"],
    seoTitle: "Email Marketing Agency | IGR Marketing",
    seoDescription: "Maximize customer lifetime value with IGR Marketing's sophisticated email marketing and lifecycle automation strategies.",
  },
  {
    id: "whatsapp-marketing",
    slug: "whatsapp-marketing",
    category: "MARKETING",
    categoryNumber: "02",
    title: "WhatsApp Marketing",
    shortDescription: "Drive instant engagement and high conversions with direct conversational marketing.",
    overview: "With unparalleled open rates, WhatsApp has become a critical channel for direct-to-consumer engagement. We implement WhatsApp marketing strategies that facilitate personalized, real-time communication. From broadcast campaigns and abandoned cart recoveries to automated customer support flows, we leverage conversational commerce to shorten the sales cycle and boost conversion rates.",
    deliverables: ["Broadcast Campaigns", "Automated Flows", "Abandoned Cart Recovery", "Customer Segmentation", "API Integration", "Performance Tracking"],
    process: ["Strategy & Opt-in Mechanics", "Flow Design", "Copywriting", "Technical Setup", "Campaign Execution", "Analysis & Iteration"],
    seoTitle: "WhatsApp Marketing Services | IGR Marketing",
    seoDescription: "Drive instant engagement and unparalleled open rates with IGR Marketing's automated WhatsApp marketing and conversational commerce.",
  },
  {
    id: "lead-generation",
    slug: "lead-generation",
    category: "MARKETING",
    categoryNumber: "02",
    title: "Lead Generation",
    shortDescription: "Architect robust systems that predictably deliver qualified sales opportunities.",
    overview: "B2B and high-ticket B2C businesses require a steady stream of qualified prospects. Our Lead Generation service engineers end-to-end systems that capture, qualify, and route high-intent leads to your sales team. We combine compelling offers, optimized landing pages, and multi-channel acquisition to fill your pipeline with opportunities that actually close.",
    deliverables: ["Lead Magnet Strategy", "Landing Page Optimization", "Multi-channel Acquisition", "Lead Scoring & Routing", "CRM Integration", "Nurture Sequences"],
    process: ["Offer Definition", "Funnel Architecture", "Traffic Generation", "Capture & Qualify", "Sales Handoff", "Pipeline Analysis"],
    seoTitle: "Lead Generation Agency | IGR Marketing",
    seoDescription: "Fill your pipeline with qualified sales opportunities. IGR Marketing architects predictable end-to-end lead generation systems.",
  },

  // 03 CREATIVE
  {
    id: "branding",
    slug: "branding",
    category: "CREATIVE",
    categoryNumber: "03",
    title: "Branding",
    shortDescription: "Crafting iconic visual identities that communicate your value and command attention.",
    overview: "Your visual identity is the silent ambassador of your brand. Our Branding service translates your strategic positioning into a compelling visual language. From logo design and typography to comprehensive brand guidelines, we create cohesive, premium identities that resonate with your target audience and ensure consistency across every touchpoint.",
    deliverables: ["Logo & Identity Design", "Typography & Color Systems", "Brand Guidelines", "Collateral Design", "Packaging Design", "Visual Asset Libraries"],
    process: ["Creative Briefing", "Moodboarding", "Concept Development", "Refinement", "Systematization", "Final Delivery"],
    seoTitle: "Branding & Visual Identity | IGR Marketing",
    seoDescription: "Craft an iconic visual identity with IGR Marketing. We design cohesive, premium brands that communicate your value and command attention.",
  },
  {
    id: "graphic-design",
    slug: "graphic-design",
    category: "CREATIVE",
    categoryNumber: "03",
    title: "Graphic Design",
    shortDescription: "High-impact visual assets that elevate your marketing and engage your audience.",
    overview: "Great design solves communication problems. Our Graphic Design services provide the ongoing visual firepower your marketing team needs. Whether it's digital ad creatives, pitch decks, social media assets, or print materials, we produce high-quality design work that stops the scroll, clarifies your message, and drives action.",
    deliverables: ["Ad Creatives", "Social Media Graphics", "Presentations & Decks", "Print Collateral", "Infographics", "UI/UX Assets"],
    process: ["Briefing", "Ideation", "Drafting", "Review & Revision", "Final Polish", "Asset Export"],
    seoTitle: "Graphic Design Services | IGR Marketing",
    seoDescription: "Elevate your marketing with high-impact visual assets. IGR Marketing delivers premium graphic design for ads, social media, and collateral.",
  },
  {
    id: "video-production-editing",
    slug: "video-production-editing",
    category: "CREATIVE",
    categoryNumber: "03",
    title: "Video Production & Editing",
    shortDescription: "Compelling visual storytelling that captures attention and drives conversions.",
    overview: "Video is the most powerful medium for digital storytelling. We produce and edit high-performing video content designed specifically for modern consumption habits. From high-end brand films to rapid-fire social media clips and performance marketing ads, our video capabilities bring your brand's narrative to life in a way that drives measurable engagement.",
    deliverables: ["Brand Films", "Social Short-Form (Reels/TikTok)", "Performance Ad Creatives", "Motion Graphics", "Corporate Promos", "Post-Production"],
    process: ["Storyboarding", "Pre-Production", "Shooting/Sourcing", "Editing", "Color & Audio", "Final Render"],
    seoTitle: "Video Production & Editing | IGR Marketing",
    seoDescription: "Bring your brand to life with IGR Marketing's video production and editing. We create compelling visual storytelling that drives engagement.",
  },
  {
    id: "creative-campaigns",
    slug: "creative-campaigns",
    category: "CREATIVE",
    categoryNumber: "03",
    title: "Creative Campaigns",
    shortDescription: "Bold, narrative-driven campaigns that cut through noise and spark conversation.",
    overview: "Sometimes, standard marketing isn't enough; you need to make a statement. Our Creative Campaigns service is designed for big launches, seasonal pushes, or brand repositioning. We develop integrated, narrative-driven campaign concepts that span multiple channels, combining striking creative with strategic distribution to maximize cultural impact and brand recall.",
    deliverables: ["Campaign Conceptualization", "Key Visuals", "Copywriting & Scripting", "Multi-Channel Rollout Plan", "Experiential Concepts", "Performance Tracking"],
    process: ["Insight Gathering", "Concept Ideation", "Asset Production", "Media Planning", "Launch", "Campaign Review"],
    seoTitle: "Creative Campaign Agency | IGR Marketing",
    seoDescription: "Launch bold, narrative-driven campaigns that cut through the noise. IGR Marketing develops integrated creative campaigns for maximum impact.",
  },

  // 04 TECHNOLOGY
  {
    id: "website-development",
    slug: "website-development",
    category: "TECHNOLOGY",
    categoryNumber: "04",
    title: "Website Development",
    shortDescription: "High-performance marketing websites engineered for speed, SEO, and conversion.",
    overview: "Your website is your ultimate conversion engine. We build marketing websites that are technically flawless, lightning-fast, and designed to convert. Leveraging modern frameworks and headless CMS architectures, we ensure your site is easy for your team to manage, loved by search engines, and provides a frictionless experience for your users.",
    deliverables: ["Custom Frontend Architecture", "CMS Integration", "Technical SEO Implementation", "Conversion Optimization", "Performance Auditing", "Analytics Integration"],
    process: ["UX/UI Design", "Technical Architecture", "Frontend Development", "Backend Integration", "QA & Testing", "Deployment"],
    seoTitle: "Website Development Services | IGR Marketing",
    seoDescription: "Build a high-performance marketing website engineered for speed, SEO, and conversion with IGR Marketing's expert web development team.",
  },
  {
    id: "web-application-development",
    slug: "web-application-development",
    category: "TECHNOLOGY",
    categoryNumber: "04",
    title: "Web Application Development",
    shortDescription: "Scalable, secure, and intuitive web applications that solve complex business problems.",
    overview: "When a standard website isn't enough, you need a custom application. We develop robust, scalable web applications tailored to your specific business logic. From internal dashboards and customer portals to full SaaS products, our engineering team builds secure, modern applications using the latest JavaScript frameworks and cloud infrastructures.",
    deliverables: ["Custom Web Apps", "SaaS Development", "Customer Portals", "API Development & Integration", "Database Design", "Cloud Architecture"],
    process: ["Requirements Scoping", "System Architecture", "Agile Development", "Security Testing", "UAT", "Launch & Maintenance"],
    seoTitle: "Web Application Development | IGR Marketing",
    seoDescription: "Develop scalable, secure, and intuitive web applications and SaaS products with IGR Marketing's expert engineering team.",
  },
  {
    id: "mobile-app-development",
    slug: "mobile-app-development",
    category: "TECHNOLOGY",
    categoryNumber: "04",
    title: "Mobile App Development",
    shortDescription: "Native and cross-platform mobile experiences that keep your brand in their pocket.",
    overview: "Mobile is where your most loyal customers live. We build high-performance mobile applications for iOS and Android that deliver frictionless, native-feeling experiences. Whether using cross-platform frameworks for speed-to-market or native languages for complex requirements, we ensure your app is intuitive, fast, and primed for high retention.",
    deliverables: ["iOS & Android Apps", "Cross-Platform (React Native)", "UI/UX Mobile Design", "App Store Optimization", "Backend Integration", "Push Notification Architecture"],
    process: ["Wireframing", "Prototyping", "Development Sprints", "Beta Testing", "App Store Submission", "Post-Launch Support"],
    seoTitle: "Mobile App Development | IGR Marketing",
    seoDescription: "Build high-performance iOS and Android mobile applications with IGR Marketing. We deliver frictionless experiences designed for retention.",
  },
  {
    id: "ecommerce-development",
    slug: "ecommerce-development",
    category: "TECHNOLOGY",
    categoryNumber: "04",
    title: "E-commerce Development",
    shortDescription: "Scalable storefronts optimized to maximize average order value and conversion rates.",
    overview: "In e-commerce, milliseconds cost money and friction kills sales. We build and optimize scalable digital storefronts on platforms like Shopify and custom headless stacks. Our development focuses heavily on conversion rate optimization, frictionless checkout flows, advanced inventory integrations, and creating digital retail experiences that drive massive revenue.",
    deliverables: ["Shopify/Headless Builds", "Custom Theme Development", "Checkout Optimization", "ERP/Inventory Integrations", "Subscription Models", "Site Speed Optimization"],
    process: ["Platform Selection", "UX Architecture", "Store Setup & Coding", "Integration Configuration", "Load Testing", "Launch"],
    seoTitle: "E-commerce Development Agency | IGR Marketing",
    seoDescription: "Build scalable, high-converting digital storefronts. IGR Marketing develops Shopify and headless e-commerce solutions engineered for revenue.",
  },
  {
    id: "crm-solutions",
    slug: "crm-solutions",
    category: "TECHNOLOGY",
    categoryNumber: "04",
    title: "CRM Solutions",
    shortDescription: "Centralize your customer data to align sales, marketing, and support operations.",
    overview: "A disorganized pipeline is a leaking pipeline. We implement and customize robust CRM solutions to centralize your customer data and streamline your revenue operations. By properly architecting systems like HubSpot or Salesforce, we ensure marketing can track attribution, sales can manage pipelines efficiently, and leadership has total visibility.",
    deliverables: ["CRM Implementation", "Data Migration", "Pipeline Architecture", "Marketing/Sales Alignment", "Custom Integrations", "Team Training"],
    process: ["Process Audit", "System Architecture", "Configuration", "Data Migration", "Workflow Automation", "Rollout"],
    seoTitle: "CRM Implementation Solutions | IGR Marketing",
    seoDescription: "Centralize data and align your revenue operations. IGR Marketing implements robust CRM solutions like HubSpot to streamline sales and marketing.",
  },
  {
    id: "ai-automation",
    slug: "ai-automation",
    category: "TECHNOLOGY",
    categoryNumber: "04",
    title: "AI Automation",
    shortDescription: "Leverage artificial intelligence to automate workflows and scale operational efficiency.",
    overview: "The future belongs to the efficient. We integrate cutting-edge AI and workflow automation into your business processes. From generative AI for content scaling to intelligent customer support bots and Zapier-driven internal operations, we help you eliminate manual redundancies, reduce costs, and operate with unprecedented speed.",
    deliverables: ["Workflow Automation", "Custom AI Chatbots", "Generative AI Integration", "Process Auditing", "Zapier/Make Integrations", "Data Pipeline Automation"],
    process: ["Efficiency Audit", "Solution Design", "API/Tool Integration", "Testing & Calibration", "Team Onboarding", "Continuous Optimization"],
    seoTitle: "AI Automation Services | IGR Marketing",
    seoDescription: "Scale operational efficiency with artificial intelligence. IGR Marketing integrates cutting-edge AI and workflow automation into your business.",
  },

  // 05 COMMERCE
  {
    id: "amazon-marketing",
    slug: "amazon-marketing",
    category: "COMMERCE",
    categoryNumber: "05",
    title: "Amazon Marketing",
    shortDescription: "Dominate the world's largest marketplace with optimized listings and precise advertising.",
    overview: "Winning on Amazon requires both organic excellence and aggressive paid strategies. We manage end-to-end Amazon operations, ensuring your products rank highly for competitive terms while maximizing profitability on Amazon Ads (PPC). From A+ content creation to inventory forecasting and Buy Box defense, we scale your presence on the platform.",
    deliverables: ["Amazon PPC Management", "Listing Optimization (SEO)", "A+ Content Creation", "Storefront Design", "Inventory Planning", "Competitor Defense"],
    process: ["Catalog Audit", "Keyword Research", "Listing Overhaul", "PPC Launch", "Bid Optimization", "Reporting"],
    seoTitle: "Amazon Marketing Services | IGR Marketing",
    seoDescription: "Dominate the Amazon marketplace. IGR Marketing provides end-to-end Amazon PPC management, listing optimization, and storefront growth.",
  },
  {
    id: "flipkart-marketing",
    slug: "flipkart-marketing",
    category: "COMMERCE",
    categoryNumber: "05",
    title: "Flipkart Marketing",
    shortDescription: "Accelerate your brand's growth and visibility on India's premier e-commerce platform.",
    overview: "Succeeding on Flipkart requires a deep understanding of its unique algorithms, promotional events, and advertising ecosystem. We provide specialized Flipkart marketing services to increase your product discoverability, optimize your product pages, and run highly efficient Flipkart Ads to drive volume and market share during crucial sale events.",
    deliverables: ["Flipkart Ads Management", "Product Listing Optimization", "Big Billion Days Strategy", "Catalog Management", "Review Strategy", "ROI Tracking"],
    process: ["Account Assessment", "Listing Optimization", "Campaign Setup", "Event Planning", "Bid Management", "Performance Analysis"],
    seoTitle: "Flipkart Marketing Services | IGR Marketing",
    seoDescription: "Accelerate your brand on India's premier e-commerce platform with IGR Marketing's specialized Flipkart advertising and optimization services.",
  },
  {
    id: "marketplace-management",
    slug: "marketplace-management",
    category: "COMMERCE",
    categoryNumber: "05",
    title: "Marketplace Management",
    shortDescription: "Unified operational control across all major third-party digital marketplaces.",
    overview: "Managing inventory, pricing, and advertising across multiple marketplaces can cause operational chaos. Our Marketplace Management service provides unified oversight of your brand across platforms like Amazon, Flipkart, Myntra, and others. We ensure pricing parity, brand consistency, and synchronized inventory so you can scale omnichannel commerce seamlessly.",
    deliverables: ["Omnichannel Strategy", "Pricing Parity Management", "Cross-Platform Inventory Sync", "Brand Protection", "Unified Reporting", "Promotional Calendaring"],
    process: ["Platform Audit", "System Integration", "Catalog Sync", "Ongoing Operations", "Dispute Management", "Strategic Growth Planning"],
    seoTitle: "Marketplace Management Agency | IGR Marketing",
    seoDescription: "Unify your omnichannel commerce. IGR Marketing provides comprehensive marketplace management across Amazon, Flipkart, Myntra, and more.",
  },
  {
    id: "quick-commerce",
    slug: "quick-commerce",
    category: "COMMERCE",
    categoryNumber: "05",
    title: "Quick Commerce",
    shortDescription: "Capture the impulse-buy market with hyper-local, high-speed commerce strategies.",
    overview: "The rise of 10-minute delivery apps has created an entirely new retail paradigm. We help FMCG and D2C brands navigate the Quick Commerce ecosystem (Blinkit, Zepto, Instamart). We optimize your product visibility, manage localized advertising, and ensure you remain top-of-mind for consumers demanding immediate fulfillment.",
    deliverables: ["Platform Onboarding", "Hyper-Local Advertising", "Q-Commerce SEO", "Assortment Strategy", "Stock Availability Monitoring", "Impulse Buy Optimization"],
    process: ["Market Feasibility", "Platform Setup", "Visibility Campaigns", "Conversion Optimization", "Data Analysis", "Scale Logistics"],
    seoTitle: "Quick Commerce Marketing | IGR Marketing",
    seoDescription: "Capture the impulse-buy market. IGR Marketing helps brands navigate and dominate Quick Commerce platforms like Blinkit, Zepto, and Instamart.",
  },

  // 06 DATA & AUTOMATION
  {
    id: "analytics-tracking",
    slug: "analytics-tracking",
    category: "DATA & AUTOMATION",
    categoryNumber: "06",
    title: "Analytics & Tracking",
    shortDescription: "Flawless measurement architecture so you can trust your data and make confident decisions.",
    overview: "Bad data leads to bad decisions. Our Analytics & Tracking service ensures your measurement architecture is technically flawless. We implement robust server-side tracking, configure GA4, set up Tag Manager, and ensure every critical user interaction is captured accurately while remaining fully compliant with modern privacy regulations.",
    deliverables: ["GA4 Implementation", "Google Tag Manager (GTM)", "Server-Side Tracking", "Event & Goal Setup", "Privacy Compliance (Consent Mode)", "Cross-Domain Tracking"],
    process: ["Measurement Audit", "Tracking Plan Design", "Technical Implementation", "Data Validation", "QA Testing", "Handoff"],
    seoTitle: "Analytics & Tracking Implementation | IGR Marketing",
    seoDescription: "Make confident decisions with flawless measurement architecture. IGR Marketing implements GA4, GTM, and server-side tracking solutions.",
  },
  {
    id: "conversion-rate-optimization",
    slug: "conversion-rate-optimization",
    category: "DATA & AUTOMATION",
    categoryNumber: "06",
    title: "Conversion Rate Optimization",
    shortDescription: "Turn more of your existing traffic into revenue through data-backed testing.",
    overview: "Increasing traffic is expensive; improving conversion rates is highly profitable. Our CRO program uses heatmaps, user session recordings, and rigorous A/B testing to identify friction points on your website. We implement iterative design and copy changes mathematically proven to increase your lead volume and e-commerce sales.",
    deliverables: ["Funnel Analysis", "Heatmap & Session Tracking", "A/B & Multivariate Testing", "UX/UI Improvements", "Copy Optimization", "Statistical Reporting"],
    process: ["Quantitative Data Review", "Qualitative Research", "Hypothesis Generation", "Test Development", "Deployment", "Result Analysis"],
    seoTitle: "Conversion Rate Optimization (CRO) | IGR Marketing",
    seoDescription: "Turn traffic into revenue. IGR Marketing's CRO services use data-backed A/B testing and UX improvements to maximize your conversion rates.",
  },
  {
    id: "dashboards-reporting",
    slug: "dashboards-reporting",
    category: "DATA & AUTOMATION",
    categoryNumber: "06",
    title: "Dashboards & Reporting",
    shortDescription: "Real-time, automated business intelligence tailored for leadership and operators.",
    overview: "Stop wrestling with messy spreadsheets. We build automated, real-time dashboards using tools like Looker Studio and Power BI that pull data from all your marketing, sales, and financial platforms into one unified view. We give leadership the high-level metrics they need, while giving operators the granular data required to execute.",
    deliverables: ["Looker Studio / Power BI Setup", "Marketing ROI Dashboards", "Sales Pipeline Visualizations", "API Data Integration", "Automated Reporting Alerts", "Custom KPI Tracking"],
    process: ["Stakeholder Interviews", "Metric Definition", "Data Integration", "Dashboard Design", "Feedback Loop", "Final Deployment"],
    seoTitle: "Custom Dashboards & Reporting | IGR Marketing",
    seoDescription: "Unify your business intelligence. IGR Marketing builds real-time, automated dashboards for marketing ROI, sales pipelines, and custom KPIs.",
  },
  {
    id: "attribution",
    slug: "attribution",
    category: "DATA & AUTOMATION",
    categoryNumber: "06",
    title: "Attribution",
    shortDescription: "Understand the true customer journey and correctly assign value to every marketing touchpoint.",
    overview: "In a multi-channel world, last-click attribution is dangerously misleading. We implement advanced attribution models that reveal the true customer journey across all touchpoints. By understanding how organic, paid, and direct channels interact before a conversion, we help you allocate your marketing budget with scientific precision.",
    deliverables: ["Multi-Touch Attribution Setup", "Customer Journey Mapping", "Marketing Mix Modeling (MMM)", "Data Blending", "Budget Allocation Strategy", "Attribution Auditing"],
    process: ["Current State Analysis", "Model Selection", "Data Aggregation", "Implementation", "Insight Generation", "Budget Realignment"],
    seoTitle: "Marketing Attribution Modeling | IGR Marketing",
    seoDescription: "Allocate your budget with scientific precision. IGR Marketing implements advanced multi-touch attribution models to map the true customer journey.",
  }
];

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return servicesData.find((s) => s.slug === slug);
}
